<a href="https://colab.research.google.com/github/ikramulkayes/Datascience_Learning/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a = np.array([[1,53,31,523,3],[59,44,6464,7,444464646]])

In [5]:
print(a)

[[        1        53        31       523         3]
 [       59        44      6464         7 444464646]]


In [6]:
print(a[1,2])

6464


In [12]:
print(a[:,1::2])
print(a[1,:])

[[ 53 523]
 [ 44   7]]
[       59        44      6464         7 444464646]


In [14]:
a[:,1:3] = [[21,12],[468,965]]

In [15]:
print(a)

[[  1  21  12 523   3]
 [ 21 468 965   4   2]]


In [21]:
b = np.array([[[45,53],[0,21]],[[89,55],[79,66]]])

In [22]:
print(b)

[[[45 53]
  [ 0 21]]

 [[89 55]
  [79 66]]]


In [23]:
b[0,1,1]

21

In [24]:
b[:,1,:] = [[55,66],[89,98]]

In [25]:
print(b)

[[[45 53]
  [55 66]]

 [[89 55]
  [89 98]]]


In [26]:
b[1,0,1]=22

In [27]:
b

array([[[45, 53],
        [55, 66]],

       [[89, 22],
        [89, 98]]])

In [28]:
b[1,0,:] = [88888,9999]

In [29]:
print(b)

[[[   45    53]
  [   55    66]]

 [[88888  9999]
  [   89    98]]]


In [33]:
b[0,:,0] = [44,44]

In [34]:
print(b)

[[[   44    53]
  [   44    66]]

 [[88888  9999]
  [   89    98]]]


In [37]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [38]:
np.full_like(a,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [39]:
np.random.randint(4,7,size=(2,3))

array([[4, 5, 6],
       [4, 6, 6]])

In [42]:
arr = np.ones((3,3))

In [49]:
np.repeat(arr,5,axis = 1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.random.rand(3,3)

array([[0.68562397, 0.00976088, 0.74465837],
       [0.06315881, 0.2418068 , 0.25038426],
       [0.50851547, 0.88068247, 0.65498384]])