<a href="https://colab.research.google.com/github/ikramulkayes/Datascience_Learning/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a = np.array([[1,53,31,523,3],[59,44,6464,7,444464646]])

In [5]:
print(a)

[[        1        53        31       523         3]
 [       59        44      6464         7 444464646]]


In [6]:
print(a[1,2])

6464


In [8]:
print(a[:,1:3])

[[  53   31]
 [  44 6464]]
